services:
  redis-frontend:
    image: redis:7.2.3-alpine3.18
    ports:
      - '6380:6379'
    restart: always
    networks:
      cdp-tenant:

  defra-id-stub:
    image: defradigital/cdp-defra-id-stub:latest
    ports:
      - '3200:3200'
    environment:
      PORT: 3200
      REDIS_HOST: redis-frontend
      REDIS_PORT: 6380
      USE_SINGLE_INSTANCE_CACHE: true
      NODE_ENV: development
      SESSION_CACHE_NAME: defraIdStubSession
    depends_on:
      redis-frontend:
        condition: service_started
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3200/health']
      interval: 5s
      start_period: 5s
      retries: 3
    networks:
      cdp-tenant:
        aliases:
          - localhost

  marine-licensing-frontend:
    build: ./
    ports:
      - '3000:3000'
    env_file:
      - 'compose/aws.env'
    environment:
      PORT: 3000
      APP_BASE_URL: http://marine-licensing-frontend.local:3000
      DEFRA_ID_ENABLED: true
      NODE_ENV: development
      USE_SINGLE_INSTANCE_CACHE: true
      MARINE_LICENSING_BACKEND_API_URL: http://marine-licensing-backend:3001
      MARINE_LICENSING_ADDRESS_LOOKUP_API_URL: http://marine-licensing-api-stub:3002/api/address-lookup/v2.1/addresses
      MARINE_LICENSING_ADDRESS_LOOKUP_OAUTH_TOKEN_URL: http://marine-licensing-api-stub:3002/oauth2/v2.0/token
      MARINE_LICENSING_ADDRESS_LOOKUP_CLIENT_ID: local-stub-client-id
      MARINE_LICENSING_ADDRESS_LOOKUP_CLIENT_SECRET: local-stub-client-secret
      MARINE_LICENSING_ADDRESS_LOOKUP_CLIENT_SCOPE: api://stub/.default
      MARINE_LICENSING_PUBLIC_REGISTER_API_URL: http://marine-licensing-public-register:3003
      ENABLE_MARINE_LICENCE: true
      ENABLE_PUBLIC_REGISTER: true
    volumes:
      - ./compose/users:/users
    command: 'sh -c "for f in /users/*.json; do curl -sS -X POST -H \"Content-Type: application/json\" -d @\"$$f\" \"http://defra-id-stub:3200/cdp-defra-id-stub/API/register\"; done & node ."'
    depends_on:
      defra-id-stub:
        condition: service_healthy
    networks:
      - cdp-tenant
    extra_hosts:
      - 'localhost:host-gateway'

networks:
  cdp-tenant:
    external: true
    driver: bridge
